sudo: required
services: docker
language: minimal
env:
  - KUBERNETES_VERSION="v1.16.13" DOCKER_IMAGE_TAG="latest-1.16" MINIKUBE_VERSION="v1.2.0"
script:
  - bash ./build.sh
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
    repo: bsycorp/kind-sts
